name: Build and publish Strecs3D Linux images
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: "Tags to apply to the image"
        required: true
        default: "latest"

env:
  IMAGE_NAME: strecs3d-linux
  IMAGE_TAGS: ${{ github.sha }} ${{ github.event.inputs.tags }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    name: Build Strecs3D Linux image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        build-mount-path: /home/runner/.local/share/containers/storage
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Install qemu dependency
      run: sudo apt-get install -y qemu-user-static

    - uses: actions/checkout@v5

    - name: Build image
      uses: redhat-actions/buildah-build@v2
      id: build-image
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        containerfiles: |
          ./Containerfile
        oci: true
        archs: amd64, arm64

    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2
      id: push-to-ghcr
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
